name: update-charts

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Host
        run: |
          # install helm
          curl -LO https://github.com/kubepack/helm/releases/download/ac-1.21.0/helm
          chmod +x ./helm
          sudo mv ./helm /usr/local/bin/helm
          # install yq
          curl -fsSL -o yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          chmod +x yq
          sudo mv yq /usr/local/bin/yq

      - name: Prepare git
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          echo $GITHUB_SERVER_URL
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_USER}@appscode.com"
          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git remote -v

      - name: Update charts
        run: |
          ./hack/scripts/trigger.sh
